name: release

on:
  push:
    tags: [ "v*" ]

jobs:
  build:
    strategy:
      matrix:
        runs-on: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn clean package -P release -D gpg.skip=true -D maven.test.skip=true -B -V --file pom.xml
    - name: Package Snail
      run: |
        mkdir -p ./build/snail/
        cp -v ./LICENSE ./build/
        cp -v ./docs/logo.ico ./build/
        cp -vr ./snail-javafx/target/lib ./build/snail/
        cp -v ./snail-javafx/target/snail.javafx-*.jar ./build/snail/
        tar -cvf snail-${{ matrix.runs-on }}.tar ./build/snail/
    - name: Upload Release Asset
      uses: actions/upload-artifact@v2
      with:
        name: snail
        path: |
          snail-*.tar
